fix workflows

diff --git a/.github/workflows/PublishNupkg.yml b/.github/workflows/PublishNupkg.yml
--- a/.github/workflows/PublishNupkg.yml
+++ b/.github/workflows/PublishNupkg.yml
@@ -5,7 +5,11 @@ on:
     workflows: [Update Version]
     types:
       - completed
-  
+
+defaults:
+  run:
+    shell: |
+           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
 env:
   BUILD_CONFIGURATION:  'Release'
 
@@ -24,10 +28,6 @@ jobs:
         with:
           dotnet-version: 6.x.x
 
-      - name: Authenticate with Github Packages
-        run:  |
-              dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name VirtualButton "https://nuget.pkg.github.com/radj307/index.json"
-              
       - name: Build
         run:  |
               dotnet build -c ${{ env.BUILD_CONFIGURATION }}
@@ -41,15 +41,8 @@ jobs:
         with:
           name: nupkg
           path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'
-
-      - name: Publish Package to Github Packages
-        run:  |
-              $dir="${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}"
-              $file=[System.IO.Path]::GetRelativePath($dir, $($(Get-ChildItem -Path "$dir" -File) -like '*.nupkg'))
-              dotnet nuget push "$file" --api-key '${{ secrets.GHP_PAT }}' --source 'https://github.com/radj307/VirtualButton'
-          
+    
       - name: Upload Package to nuget.org
         uses: tedd/publish-nuget-neo@v1.0.2
         with:
           NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
-          INCLUDE_SYMBOLS: true
diff --git a/.github/workflows/UpdateVersion.yml b/.github/workflows/UpdateVersion.yml
--- a/.github/workflows/UpdateVersion.yml
+++ b/.github/workflows/UpdateVersion.yml
@@ -1,35 +1,48 @@
-name: 'Update Version'
+name: Publish Nuget Package
 
 on:
-  push:
-    tags: '[0-9]+.[0-9]+.[0-9]+-?**'
-  workflow_dispatch:
+  workflow_run:
+    workflows: [Update Version]
+    types:
+      - completed
+
+defaults:
+  run:
+    shell: |
+           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
+env:
+  BUILD_CONFIGURATION:  'Release'
 
 jobs:
-  # This job is required because C# is assholes and dotnet publish refuses to use the version number set by the SetVersion.ps1 script.
-  update-version-number:
-    runs-on:  windows-2022
-    
+  build:
+    runs-on: windows-latest
+    env:
+      DOTNET_NOLOGO:                true
+      DOTNET_CLI_TELEMETRY_OPTOUT:  true
+
     steps:
       - uses: actions/checkout@v3
+      
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v2
         with:
-          fetch-depth:  0
-        
-      - name:   Run SetVersion.ps1
-        run:    |
-                cd ${{github.workspace}}
-                .\SetVersion.ps1
-        shell:  |
-                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
-        
-      - name:   Fetch History
-        run:    git fetch
+          dotnet-version: 6.x.x
 
-      - name:   Push Changes
-        run:    |
-                cd ${{github.workspace}}
-                git config user.name github-actions
-                git config user.email github-actions@github.com
-                git add -A
-                git commit -m "Update .csproj Version Numbers"
-                git push origin
+      - name: Build
+        run:  |
+              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
+              
+      - name: Pack
+        run:  |
+              dotnet pack -c ${{ env.BUILD_CONFIGURATION }}
+              
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: nupkg
+          path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'
+    
+      - name: Upload Package to nuget.org
+        uses: tedd/publish-nuget-neo@v1.0.2
+        with:
+          NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
