Update UpdateVersion.yml

diff --git a/.github/workflows/UpdateVersion.yml b/.github/workflows/UpdateVersion.yml
--- a/.github/workflows/UpdateVersion.yml
+++ b/.github/workflows/UpdateVersion.yml
@@ -1,48 +1,50 @@
-name: Publish Nuget Package
+###
+# Name:          UpdateVersion.yml
+# Project Lang:  C# (not required)
+# Description:   Github actions workflow that runs a PowerShell script to update the version number present in a project's .csproj file.
+#                This needs to be done in an entirely separate workflow, otherwise actions/checkout & dotnet get confused by each other and refuse to use the correct version number.
+###
+
+env:
+  SCRIPT: '${{github.workspace}}/SetVersion.ps1'
+  # ^ Set this to the location of the powershell script to run.
+  
+############################################################
+name: 'Update Version'
 
 on:
-  workflow_run:
-    workflows: [Update Version]
-    types:
-      - completed
+  push:
+    tags: '[0-9]+.[0-9]+.[0-9]+-?**'
+  workflow_dispatch:
 
+# Set default windows shell
 defaults:
   run:
-    shell: |
-           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
-env:
-  BUILD_CONFIGURATION:  'Release'
-
+    shell:  |
+            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
 jobs:
-  build:
-    runs-on: windows-latest
-    env:
-      DOTNET_NOLOGO:                true
-      DOTNET_CLI_TELEMETRY_OPTOUT:  true
-
+  # This job is required because C# is assholes and dotnet publish refuses to use the version number set by the SetVersion.ps1 script.
+  update-version-number:
+    runs-on:  windows-2022
+    
     steps:
       - uses: actions/checkout@v3
-      
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v2
         with:
-          dotnet-version: 6.x.x
+          fetch-depth:  0
+        
+      - name:   Run SetVersion.ps1
+        run:    |
+                cd ${{github.workspace}}
+                .\SetVersion.ps1
+                
+      - name:   Fetch History
+        run:    git fetch
 
-      - name: Build
-        run:  |
-              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
-              
-      - name: Pack
-        run:  |
-              dotnet pack -c ${{ env.BUILD_CONFIGURATION }}
-              
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: nupkg
-          path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'
-    
-      - name: Upload Package to nuget.org
-        uses: tedd/publish-nuget-neo@v1.0.2
-        with:
-          NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
+      - name:   Push Changes
+        run:    |
+                cd ${{github.workspace}}
+                git config user.name github-actions
+                git config user.email github-actions@github.com
+                git add -A
+                git commit -m "Update .csproj Version Numbers"
+                git push origin
